        <!-- projects -->
        <section id="projects" class="tab-pane active"><!-- remove "active" if no screen content wanted -->
          <article id="project#1">
            <h4>Finance</h4>
            <p>
              <!-- application description: draft #1 -->
              This web application allows users to manage their own stock portfolio. 
              Users initially register themselves for an account, which allows them to login and view their portfolio.
              Users can query the real-time market price of any particular stock, data which is generated by Yahoo! Finance.
              They can also buy any number of shares of a particular stock, while also being able to sell their entire 
              holding of a particular stock.
              The users can also deposit any amount of additional money into their account.
              In addition, users can view specific details of all their buying and selling transactions.
              They can also change their current password.
              Finally, users can reset their password if they cannot login, which sends their email address a new random 
              password (if their details are verified).
            </p>
            <a href=""><!-- specify -->
              <img alt="Portfolio Image" src="static/finance-draft.jpg" width="600px" height="400px"/>
            </a>
            <p>
              <!-- technical description: draft #0 -->
Within the project directory there are individual directories which each contain auxiliary files, main (controller) files, and template files.
The auxiliary files, within the includes directory, contain programming language (PHP) code that configures various server settings, and additionally code which is packaged into individual packages (called functions) which allows a particular block of code to be reused in differing parts of the application (e.g. on each page) more efficiently.
The controller files, within the public directory, contain mainly PHP code that dictates the functional behaviour of the application. Each main controller is responsible for a single page of the application, and also makes use of the differing auxiliary code functions that assists this.
The templates files, within the views directory, contain mainly markup language (HTML) that can allow the user to enter data from the browser (which can be processed by a controller). These templates can also determines what output data is visible on each page in the browser, and also structures how this data is seen. These templates also have markers that allow the aesthetics of what is shown on each page to be controlled via a style language (CSS).
            </p>
          </article>
        </section>

        <section id="about" class="tab-pane">
          <p>
            <!-- about: draft #1 -->
            Hello. My name is Nick. I'm an Australian-born aspiring Web Developer. 
            I have programming experience in differing forms and languages, due to varying work and education.
            My experience includes developing mathematical code that interfaced with commercial software as part of 
            completing a research degree at a research-intensive university, along with improving an existing codebase 
            during an engineering internship within a multinational corporation (which was based in Germany). 
            As an aside, I have also worked within the Arts & Distribution industries within Australia. 
            In my free time, I enjoy playing <i>Futsal</i> and acoustic guitar. This is a picture of my cat. He's friendly.
          </p>
          <img alt="Cat Image" src="../static/my-cat.jpg" width="375px" height="300px"/>
        </section>

        <!-- contact -->
        <section id="contact" class="tab-pane">
          <!-- my details -->
          <div class="col-xs-6 col-xs-offset-6" id="my-details">
            Nicholas Howlett
            <br>
            m: +61 451 653 170
            <br>
            e: nicholashowlett1@gmail.com
          </div>
          <!-- form details -->
          <div id="form">
            <form action="<?php $_PHP_SELF ?>" method="POST">
              <div class="form-group">
                <div class="row">
                  <div class="col-xs-6">
                    <input class="form-control" id="name" type="text" name="name" placeholder="Your name"
<?php
    // repopulate name if validated (access $validatedName value via superglobal array)
    if ($GLOBALS['validatedName'] == true) echo 'value="' . $_POST['name'] . '"';
?>
                    />
                  </div>
                </div>
              </div>
              <div class="form-group">
                <div class="row">
                  <div class="col-xs-6">
                    <input class="form-control" id="email" type="text" name="email" placeholder="Your email address"
<?php    
    // repopulate email if validated
    if ($validatedEmail == true) echo 'value="' . $_POST["email"] . '"';
?>
                    />
                  </div>
                </div>
              </div>
              <div class="form-group">           
<?php   
    // repopulate message if validated
    if ($validatedMessage == true):
        echo '<textarea class="form-control" id="message" rows="5" name="message" placeholder="Message">' . $_POST["message"] . '</textarea>';
    else:
        echo '<textarea class="form-control" id="message" rows="5" name="message" placeholder="Message"></textarea>';
    endif;
?>
              </div>
              <div class="form-group" id="button">
                <button class="btn btn-default" type="submit">Send</button>
              </div>
            </form>
          </div>
        </section>
